// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package pgstore

import (
	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type User struct {
	ID           uuid.UUID        `db:"id" json:"id"`
	Email        string           `db:"email" json:"email"`
	PasswordHash string           `db:"password_hash" json:"password_hash"`
	CreatedAt    pgtype.Timestamp `db:"created_at" json:"created_at"`
	UpdatedAt    pgtype.Timestamp `db:"updated_at" json:"updated_at"`
	Permissions  []byte           `db:"permissions" json:"permissions"`
	IsActive     pgtype.Bool      `db:"is_active" json:"is_active"`
	IsVerified   pgtype.Bool      `db:"is_verified" json:"is_verified"`
}
